SPRITE_SCALING = 0.5
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
PLAYER_START_X = 400
PLAYER_START_Y = 50
PLAYER_START_LIVES = 3
PLAYER_ROTATE_SPEED = 5
PLAYER_THRUST = 0.05
PLAYER_SHOT_SPEED = 4
PLAYER_SPEED_LIMIT = 5
PLAYER_INVINCIBILITY_SECONDS = 5
PLAYER_FIRE_RATE = 0.2
PLAYER_SHOT_RANGE = 400
PLAYER_THRUST_KEY = 65362
PLAYER_FIRE_KEY = 32
EXIT_SETTINGS_KEY = 65307
PLAYER_TURN_RIGHT_KEY = 65363
PLAYER_TURN_LEFT_KEY = 65361
ASTEROIDS_PR_LEVEL = 5
ASTEROIDS_SPEED = 1
ASTEROID_SCORE_VALUES = [
    20,
    30,
    40,
    50,
]
ASTEROIDS_PR_SPLIT = 2
UFO_SPEED = 2
UFO_DIR_CHANGE_RATE = 3
UFO_SPAWN_RATE = 10
UFO_POINTS_REWARD = 300
UFO_SHOT_SPEED = 2
UFO_SHOT_RANGE = 200
UFO_FIRE_RATE = 1.5
UFO_SIZE_SMALL = 0.9
UFO_SIZE_BIG = 1.5
TITLE_X = 400
TITLE_Y = 450
BUTTON_X = 400
BUTTON_Y = 300
SETTINGS_BUTTON_X = 400
SETTINGS_BUTTON_Y = 200