# this is the config file for the project, storing all the game file constants

SPRITE_SCALING = 0.5

# screen_constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# player_constants
PLAYER_START_X = 400
PLAYER_START_Y = 50
PLAYER_START_LIVES = 3
PLAYER_ROTATE_SPEED = 5
PLAYER_THRUST = 0.05  # speed gained from thrusting
PLAYER_SHOT_SPEED = 4
PLAYER_SPEED_LIMIT = 5
PLAYER_INVINCIBILITY_SECONDS = 5
PLAYER_FIRE_RATE = 0.2
PLAYER_SHOT_RANGE = 400

# asteroid_constants
ASTEROIDS_PR_LEVEL = 5
ASTEROIDS_SPEED = 1
ASTEROID_SCORE_VALUES = [20, 30, 40, 50]
ASTEROIDS_PR_SPLIT = 2

# ufo_constants
UFO_SPEED = 2  # both for x and y note: has to be int
UFO_DIR_CHANGE_RATE = 3
UFO_SPAWN_RATE = 10  # seconds
UFO_POINTS_REWARD = 300
UFO_SHOT_SPEED = 2
UFO_FIRE_RATE = 1.5
UFO_SIZE_SMALL = 0.9
UFO_SIZE_BIG = 1.5

# UI
TITLE_X = 400
TITLE_Y = 450
BUTTON_X = 400
BUTTON_Y = 300
