# this is the config file for the project, storing (almost) all the game file constants

SPRITE_SCALING = 0.5

# screen_constants
SCREEN_WIDTH = 800  # px
SCREEN_HEIGHT = 600  # px

# player_constants
PLAYER_START_X = 400  # px
PLAYER_START_Y = 300  # px
PLAYER_START_LIVES = 3
PLAYER_ROTATE_SPEED = 5  # px/update
PLAYER_THRUST = 0.05  # speed gained from thrusting
PLAYER_SHOT_SPEED = 4  # px/update
PLAYER_SPEED_LIMIT = 5  # px/update
PLAYER_INVINCIBILITY_SECONDS = 5  # secs
PLAYER_FIRE_RATE = 0.2  # secs
PLAYER_SHOT_RANGE = 400  # px
PLAYER_SHOT_FADE = -2 #alpha

# asteroid_constants
ASTEROIDS_MINIMUM_SPAWN_DISTANCE_FROM_PLAYER = 350 # px
ASTEROIDS_PR_LEVEL = 5
ASTEROIDS_SPEED = 1  # px/update
ASTEROID_SCORE_VALUES = [20, 30, 40, 50]  # points
ASTEROIDS_PR_SPLIT = 2

# ufo_constants
UFO_SPEED = 2  # px/update. both for x and y note: has to be int
UFO_DIR_CHANGE_RATE = 3  # secs
UFO_SPAWN_RATE = 10  # seconds
UFO_POINTS_REWARD = 300  # points
UFO_SHOT_SPEED = 2  # px/update
UFO_SHOT_RANGE = 200  # px
UFO_FIRE_RATE = 1.5  # secs
UFO_SIZE_SMALL = 0.9  # multiplier for original file
UFO_SIZE_BIG = 1.5  # multiplier for original file
PLAYER_ENGINE_SHAKE = 20 # The maximum + minimum of the shaking of the particles
EXPLOSION_PARTICLE_AMOUNT = 500
EXPLOSION_PARTICLE_SPEED = 5
EXPLOSION_PARTICLE_LIFETIME_MIN = 0.1
EXPLOSION_PARTICLE_LIFETIME_MAX = 2
EXPLOSION_PARTICLE_SIZE = 5

# UI
TITLE_X = 400  # pCha
TITLE_Y = 450  # px
BUTTON_X = 400  # px
BUTTON_Y = 300  # px
